package sgcan.intercom.ms_services.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Mono;
import sgcan.intercom.ms_services.bussines.FitoBussines;
import sgcan.intercom.ms_services.bussines.TokenBussines;
import sgcan.intercom.ms_services.model.Token;

@RestController
@RequestMapping("/api/v1/beer")
public class BeerController {
    @Autowired
    public TokenBussines tokenBussines;
    @Autowired
    public FitoBussines fitoBussines;
    @GetMapping("/random")
    Mono<String> getRandom(){
        return fitoBussines.getFito("eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyLXhlUFh6OVRYY0hFQ3ZieEhsY2x5YzlYSEw2TmtfUllsY2ZNZG9EckRBIn0.eyJleHAiOjE3MjA3MzU0ODMsImlhdCI6MTcyMDczNTE4MywianRpIjoiZDZkNzQyY2QtOWMyYS00NDhiLThlYmMtYjkzMDllYzA3MDdiIiwiaXNzIjoiaHR0cHM6Ly9henVyZS1pbnRlcmNvbS5kZG5zLm5ldDoyODQ0My9yZWFsbXMvaW50ZXJjb20iLCJhdWQiOlsiaW50ZXJjb20tYXBpIiwiYWNjb3VudCJdLCJzdWIiOiJmNzk4NDZkOS1iM2FiLTRlNWItYjkxNi1mZWI3NzQ4Njc0MjAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ2dWNlLXBlcnUiLCJhY3IiOiIxIiwicmVzb3VyY2VfYWNjZXNzIjp7InZ1Y2UtcGVydSI6eyJyb2xlcyI6WyJ1bWFfcHJvdGVjdGlvbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJkb2N1bWVudG9zIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImNsaWVudEhvc3QiOiIxNjguMTIxLjIzNi40NSIsImNsaWVudElkIjoidnVjZS1wZXJ1IiwiZW50aWRhZCI6IkRWVUNFUFQiLCJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWludGVyY29tIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdLCJuYW1lIjoiRFZVQ0VQVCIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC12dWNlLXBlcnUiLCJnaXZlbl9uYW1lIjoiRFZVQ0VQVCIsImNsaWVudEFkZHJlc3MiOiIxNjguMTIxLjIzNi40NSIsImZhbWlseV9uYW1lIjoiIiwicGFpcyI6IlBFIn0.qIVc3B3EoRHxlNISzltxq4xsfjnJaRgaBxWhtnJrCqmQ3KqqNv4-1H7glNrTWfxEsgNBtTgMw917PKw-RCWiHvFlTQmzBYOAcGwtvg9sAeWWFOinl3tOQCNgdTiv5wbUzHrhgjFo2wubPLMNzbkc6pGfAPRGlmRyRj1T5sy7JKtehDMPPF5JzNLsYfO4NMLbnprvE3IBoEZTL76fPgUYodMfFL7IEIEL5VaZQ0HDcT4lIQsuS8FiZxOaBXiglwUodZM-Ckdfv4juojt6Akz_a6yHuck8Q7K5bcM_xG-1KQCdNRSrOjoLilo7EBDF7-3Blf0uqXKIpzrWJzWfIemlbQ");

    }
}
